version: "3.8"

services:
  gateway:
    container_name: gateway 
    hostname: gateway
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file: ./nginx/.env
    depends_on:
      - auth
      - git
      - ticket
      - vms
    image: docker.io/vutrongquang/gateway

  auth:
    container_name: auth 
    hostname: auth
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: auth
    restart: always
    ports:
      - 6801:6801
    user: root
    env_file: ./apps/auth/.env
    environment:
      - CA_AUTH_TICKET_SERVICE_HOST=http://ticket
      - CA_AUTH_GIT_SERVICE_HOST=http://git
    image: docker.io/vutrongquang/auth

  git:
    container_name: git 
    hostname: git
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: git
    restart: always
    ports:
      - 6802:6802
    user: root
    env_file: ./apps/git/.env
    environment:
      - CA_GIT_USERS_SERVICE_HOST=http://auth
      - CA_GIT_AUTH_SERVICE_HOST=http://auth
      - CA_GIT_TICKET_SERVICE_HOST=http://ticket
    image: docker.io/vutrongquang/git

  ticket:
    container_name: ticket 
    hostname: ticket
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: ticket
    restart: always
    ports:
      - 6803:6803
    user: root
    env_file: ./apps/ticket/.env
    environment: 
      - CA_TICKET_GIT_SERVICE_HOST=http://git
      - CA_TICKET_USERS_SERVICE_HOST=http://auth
      - CA_TICKET_AUTH_SERVICE_HOST=http://auth
    image: docker.io/vutrongquang/ticket

  vms:
    container_name: vms 
    hostname: vms
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: vms
    restart: always
    ports:
      - 6804:6804
    user: root
    env_file: ./apps/vms/.env
    image: docker.io/vutrongquang/vms
    volumes:
      - /home/quang_vt204299/vms:/ca

networks:
  default:
    name: ca-network