version: "3.8"

services:
  gateway:
    container_name: gateway 
    hostname: gateway
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 8080:8000
    env_file: ./nginx/.env
    depends_on:
      - auth
      - git
      - ticket
      - vms
      - scan
      - mail
    image: docker.io/vutrongquang/gateway

  auth:
    container_name: auth 
    hostname: auth
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: auth
    restart: always
    ports:
      - 6801:6801
    user: root
    env_file: ./apps/auth/.env
    environment:
      - CA_AUTH_TICKET_SERVICE_HOST=http://ticket
      - CA_AUTH_GIT_SERVICE_HOST=http://git
      - CA_AUTH_MONGO_ADDRESSES=103.166.185.48:6807
      - CA_AUTH_REDIS_HOST=103.166.185.48
      - CA_AUTH_MAIL_SERVICE_HOST=http://mail
    image: docker.io/vutrongquang/auth

  git:
    container_name: git 
    hostname: git
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: git
    restart: always
    ports:
      - 6802:6802
    user: root
    env_file: ./apps/git/.env
    environment:
      - CA_GIT_USERS_SERVICE_HOST=http://auth
      - CA_GIT_AUTH_SERVICE_HOST=http://auth
      - CA_GIT_TICKET_SERVICE_HOST=http://ticket
      - CA_GIT_CLIENT_ID=Ov23liAKvwqR0iILNsiC
      - CA_GIT_CLIENT_SECRET=a370820af2811e1329ced80356511229d40590e4
      - CA_GIT_MONGO_ADDRESSES=103.166.185.48:6807
      - CA_GIT_REDIS_HOST=103.166.185.48
    image: docker.io/vutrongquang/git

  ticket:
    container_name: ticket 
    hostname: ticket
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: ticket
    restart: always
    ports:
      - 6803:6803
    user: root
    env_file: ./apps/ticket/.env
    environment: 
      - CA_TICKET_GIT_SERVICE_HOST=http://git
      - CA_TICKET_USERS_SERVICE_HOST=http://auth
      - CA_TICKET_AUTH_SERVICE_HOST=http://auth
      - CA_TICKET_MONGO_ADDRESSES=103.166.185.48:6807
      - CA_TICKET_REDIS_HOST=103.166.185.48
    image: docker.io/vutrongquang/ticket

  vms:
    container_name: vms 
    hostname: vms
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: vms
    restart: always
    ports:
      - 6804:6804
    user: root
    env_file: ./apps/vms/.env
    environment:
      - CA_VMS_TICKET_SERVICE_HOST=http://ticket
      - CA_VMS_GIT_SERVICE_HOST=http://git 
      - CA_VMS_MONGO_ADDRESSES=103.166.185.48:6807
      - CA_VMS_REDIS_HOST=103.166.185.48    
    image: docker.io/vutrongquang/vms

  scan:
    container_name: scan 
    hostname: scan
    build:
      context: .
      dockerfile: ./Dockerfile.Scan
      args:
        module: scan
    restart: always
    ports:
      - 6805:6805
    user: root
    env_file: ./apps/scan/.env
    environment:
      - CA_SCAN_MONGO_ADDRESSES=103.166.185.48:6807
      - CA_SCAN_REDIS_HOST=103.166.185.48
    image: docker.io/vutrongquang/scan

  mail:
    container_name: mail 
    hostname: mail
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: mail
    restart: always
    ports:
      - 6806:6806
    user: root
    environment:
      - CA_MAIL_MONGO_ADDRESSES=103.166.185.48:6807
      - CA_MAIL_REDIS_HOST=103.166.185.48
    env_file: ./apps/mail/.env
    image: docker.io/vutrongquang/mail

networks:
  default:
    name: ca-network