version: "3.8"

services:
  gateway:
    container_name: gateway 
    hostname: gateway
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file: ./nginx/.env
    depends_on:
      - auth
      - git
      - ticket
    image: docker.io/vutrongquang/gateway

  auth:
    container_name: auth 
    hostname: auth
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: auth
    restart: always
    ports:
      - 6801:6801
    user: root
    env_file: ./apps/auth/.env
    image: docker.io/vutrongquang/auth

  git:
    container_name: git 
    hostname: git
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: git
    restart: always
    ports:
      - 6802:6802
    user: root
    env_file: ./apps/git/.env
    image: docker.io/vutrongquang/git

  ticket:
    container_name: ticket 
    hostname: ticket
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: ticket
    restart: always
    ports:
      - 6803:6803
    user: root
    env_file: ./apps/ticket/.env
    image: docker.io/vutrongquang/ticket


networks:
  default:
    name: ca-network