version: "3.8"

services:
  gateway:
    container_name: gateway 
    hostname: ca.gateway
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file: ./nginx/.env
    depends_on:
      - auth
    image: docker.io/vutrongquang/gateway

  auth:
    container_name: auth 
    hostname: ca.auth
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: auth
    restart: always
    ports:
      - 6801:6801
    user: root
    env_file: ./apps/auth/.env
    image: docker.io/vutrongquang/auth


networks:
  default:
    name: ca-network