version: "3.8"

services:
  gateway:
    container_name: gateway 
    image: docker.io/vutrongquang/gateway
    restart: always
    ports:
      - 8000:8000
    env_file: ./nginx/.env
    depends_on:
      - auth
      - mail
      - file

  auth:
    container_name: auth 
    image: docker.io/vutrongquang/auth
    restart: always
    ports:
      - 6801:6801
    user: root
    env_file: ./apps/auth/.env

networks:
  default:
    name: ca-network
